# -*- coding: utf-8 -*-
"""clean_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u8sZuYMf_aVQfzT9_rvt2RXjIGxQ-kZh
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display

# Set display options for clarity
pd.set_option('display.max_columns', None)
print('Environment setup complete.')

df = pd.read_csv('ebay_tech_deals.csv')
display(df.head())
display(df.info())
display(df.describe())

print('Missing values in each column:')
display(df.isnull().sum())

df_filled = df.copy()

df_filled['price'] = (
    df_filled['price']
    .astype(str)
    .str.replace("US \$", "", regex=True)
    .str.replace("\$", "", regex=True)
    .str.replace(",", "", regex=True)
    .str.strip()
)
df_filled['original price'] = (
    df_filled['original price']
    .astype(str)
    .str.replace("US \$", "", regex=True)
    .str.replace("\$", "", regex=True)
    .str.replace(",", "", regex=True)
    .str.strip()
)
display(df_filled.head())

df_filled['original price'] = df_filled['original price'].replace(['N/A', '', 'nan', 'NaN'], pd.NA)
display(df_filled.head())

missing = df_filled['original price'].isna()
df_filled.loc[missing, 'original price'] = df_filled.loc[missing, 'price']

display(df_filled.head())

df_filled['shipping'] = df_filled['shipping'].fillna('Shipping info unavailable')
display(df_filled)

df_filled['price'] = pd.to_numeric(df_filled['price'], errors='coerce')
df_filled['original price'] = pd.to_numeric(df_filled['original price'], errors='coerce')
display(df_filled.head())

df_filled['discount_percentage'] = ((1 - df_filled['price'] / df_filled['original price']) * 100).round(2)
display(df_filled[['price', 'original price', 'discount_percentage']].head())

df_filled.to_csv("cleaned_ebay_deals.csv", index=False)